### ISSUE TITLE
Download/Save & view past tracks?

### ISSUE THREAD

**Issue by fsparv** [hankhank10/findmyplane-client#9]
What I want is to fly in MSFS, and then obtain something that looks like the flight aware data/map for my flight (after the fact). I can't tell if this software allows that or not. I see a map with a line in one of the images, but it also talks about uploading a flight plan, and I can't fathom why I would want to do that... I want to do things like judge if my turns around a point were circular or not, and then hop back in the sim try again and see if I did any better.

After looking at https://findmyplane.live/ and your GitHub readme, all I know now is that it seems to be the case that my movement might show up on a map while I'm in game (and it's easy to use, written in python, open source, and a bunch of other very nice things that don't actually represent functionality), which is nifty... but ultimately not terribly useful unless I can download/save the flight and view it later, compare it with previous flights (even if just visually  in separate windows), etc. so I'm either suggesting those features or suggesting you document them better ;)

**Comment by hankhank10** [comment]
FindMyPlane is designed to assist with real time navigation. It displays your current location and the historical path, but it doesn't allow you to download it or save it after the fact.

The purpose of uploading a flight plan is to allow users to track their location current vs their plan.

If you are looking for flight logging software then there are many options such as [Volanta](https://volanta.app/features/)
